-- Photographs for 67 events that had none.
--
-- All from Wikimedia Commons under licences that allow commercial use with credit; each is
-- credited on its event page and on /image-credits (see src/data/event-photo-credits.json).
-- Every one was looked at before it was chosen. Each says what it shows: the event itself,
-- the professional race on the same roads, or a place on or at the route — never a stock
-- picture passed off as the event. Only fills blanks: an image set in the admin is kept.

update events e set img = v.file
from (values
  ('maratona-dles-dolomites', 'Maratona dles Dolomites - Dolomites.jpg'),
  ('unbound-gravel', 'Dirty Kanza.png'),
  ('leadville-trail-100-mtb', 'Mount Massive and Leadville from 7th Street.jpg'),
  ('sea-otter-classic', 'Todd Wells Sea Otter Finish.JPG'),
  ('absa-cape-epic', 'Cape epic petter fagerhaug 4.jpg'),
  ('cape-town-cycle-tour', '2024 Cape Town Cycle Tour (8).jpg'),
  ('lake-taupo-cycle-challenge', 'Taupo Cycle Challenge 02.jpg'),
  ('motatapu-mtb', 'Motatapu Valley,Otago Region, New Zealand. - panoramio.jpg'),
  ('great-victorian-bike-ride', 'GVBR Tent City at Anglesea Pano, Vic, jjron, 09, 04.12.2009.jpg'),
  ('thunderbolts-adventure', 'Barrington Tops - panoramio (2).jpg'),
  ('gravel-n-granite', 'Tenterfield, New South Wales CBD.jpg'),
  ('seven-gravel-race', 'Vasse Highway, main street of Nannup, Western Australia, January 2023 01.jpg'),
  ('vatternrundan', 'Vätternrundan 2013.jpg'),
  ('nove-colli', 'Partenza-nove-colli-cesenatico.JPG'),
  ('paris-roubaix-challenge', 'Paris-Roubaix 2021 KM39.jpg'),
  ('liege-bastogne-liege-challenge', 'Liège-Bastogne-Liège 2014 Echappée du jour Côte de Wanne.JPG'),
  ('amstel-gold-race-toerversie', '2019 Amstel Gold Race 074.jpg'),
  ('lardechoise', 'Ardéchoise Mariac Ravitaillement.jpg'),
  ('alpenbrevet', 'Alpenbrevet 2024 Anfahrt Furka 1.jpg'),
  ('tour-transalp', 'Arnoga ^ Schwalbe-Tour-Transalp - panoramio.jpg'),
  ('the-gralloch', 'Galloway Forest Park.JPG'),
  ('grinduro-scotland', 'Drumlanrig Castle FZ82 P1080141.jpg'),
  ('nova-eroica-prosecco-hills', 'Tra le vigne di Collagù - wikiraduno Alle colline del prosecco abc 02.jpg'),
  ('salzkammergut-trophy', 'Bad Goisern SKGT2024.jpg'),
  ('megavalanche-alpe-dhuez', 'Megavalanche-2010-Huez.jpg'),
  ('bwr-arizona', 'McDowell Mountain Regional Park, Arizona, US.jpg'),
  ('bwr-mexico', 'Plaza principal, Tequisquiapan Querétaro. México.jpg'),
  ('bc-bike-race', 'ZF-1931-66284-1-001.jpg'),
  ('breck-epic', 'Racing in Breck.jpg'),
  ('pisgah-111', '170730-fs-pisgah-cmr-681 23543772678 o (38863300350).jpg'),
  ('swiss-epic', 'Swiss Epic.jpg'),
  ('ragbrai', 'USAF RAGBRAI cyclists.jpg'),
  ('hotter-n-hell-hundred', 'Hotter''N Hell Hundred Ride (9630742494).jpg'),
  ('tour-de-okinawa-citizen-race', 'Alan Marangoni vince al Tour de Okinawa, 2018.jpg'),
  ('letape-cunha', 'Morros em Cunha, São Paulo 1.jpg'),
  ('la-ruta-de-los-conquistadores', 'Ruta de Los Conquistadores, Costa Rica.jpg'),
  ('amys-gran-fondo', 'Great Ocean Road, Lorne, Australia - Feb 2012.jpg'),
  ('we-ride-flanders', 'Tour des Flandres cyclo 2017- Oude Kwaremont VF.jpg'),
  ('gran-fondo-strade-bianche', 'Strade Bianche 2014 (13504915215).jpg'),
  ('levis-granfondo', 'King Ridge Road - Terry Morse.jpg'),
  ('sbt-grvl', 'Steamboat Springs downtown.jpg'),
  ('whaka-100', 'Redwoods Forest Rotorua 37.jpg'),
  ('le-race', 'Akaroa, New Zealand.jpg'),
  ('otway-odyssey', 'Forrest Station Street.JPG'),
  ('tour-de-brisbane', 'Story Bridge Panorama.jpg'),
  ('dragon-ride', 'The Rhigos (geograph 6234062).jpg'),
  ('otztaler-radmarathon', 'Timmelsjoch Panorama.jpg'),
  ('quebrantahuesos', 'Start of Quebrantahuesos 2011.jpg'),
  ('la-stelvio-santini', 'Stelvio Pass Bormio side 2.jpg'),
  ('dreilandergiro', 'Stelvio Pass Bolzano side 1.jpg'),
  ('mondsee-5-seen-radmarathon', 'Aerial image of the Mondsee (view from the southeast).jpg'),
  ('arlberg-giro', 'Silvretta-Hochalpenstrasse 02.jpg'),
  ('cyclotour-du-leman', 'Lake Geneva in Lausanne.jpg'),
  ('gran-fondo-il-lombardia', 'Il Lombardia 2023 - 001 Pogacar.jpg'),
  ('milano-sanremo-amatori', 'Milano Sanremo 2005.jpg'),
  ('nova-eroica-buonconvento', 'Crete senesi - Asciano (Siena).jpg'),
  ('grand-raid-bcvs', 'Becs de Bosson depuis le Pas de Lona.jpg'),
  ('the-big-lost-rebeccas-private-idaho', 'Ketchum, Idaho street July 2024.jpg'),
  ('whiskey-off-road', 'Prescott National Forest region 2015 015.jpg'),
  ('iceman-cometh-challenge', 'Kalkaska.jpg'),
  ('rbc-granfondo-whistler', 'Sea to Sky Highway and Howe Sound at Porteau Road.jpg'),
  ('triple-bypass', 'Průsmyk Loveland Pass, 3655 m n.m., rozvodí Atlatik-Pacifik; jih Colorada, Front Range0241112 123004.jpg'),
  ('blue-sky-hill-climb', 'Mt Evans Road P6040208.jpg'),
  ('grinduro-california', 'Quincy, California from Q on mountain..JPG'),
  ('mt-fuji-hill-climb', 'Fuji Subaru Line Fifth Station 02.JPG'),
  ('yak-attack', 'Muktinath Valley, View of Thorong La Pass, Mountains, Nepal.jpg'),
  ('wines2whales', 'Lourensford Wine estate 03.jpg')
) as v(slug, file)
where e.slug = v.slug and (e.img is null or e.img = '');

select count(*) filter (where img is not null) as with_photo, count(*) as total from events where status = 'published';
