-- Event photos, and the launch set of events loaded into the database so they can be
-- edited in the admin rather than shipped in code.

alter table events add column if not exists img text;

insert into events (slug, name, organiser, url, country, region, town_id, next_date, "window", km, vert, discipline, month, note, verified)
values
  ('peaks-challenge-falls-creek','Peaks Challenge Falls Creek','Bicycle Network','https://bicyclenetwork.com.au/rides-and-events/peaks-challenge/','Australia','Victorian Alps','bright','2027-03-07','Early March, annually','{235}'::integer[],4000,'road','March','The ride Australians just call Three Peaks: 235 km from Falls Creek over Tawonga Gap, Mt Hotham and back up Falls Creek itself, with a 13-hour cutoff. It is the longest, hardest one-day mass-participation road ride on the Australian calendar, and the last climb starts when you have already ridden 200 km.','2026-09-05'),
  ('around-the-bay','Around the Bay','Bicycle Network','https://bicyclenetwork.com.au/rides-and-events/around-the-bay/','Australia','Victoria',null,'2026-10-18','October, annually','{220}'::integer[],null,'road','October','A ride around Port Phillip Bay from Melbourne, with six options from a short family ride up to the full 220 km circuit. Flat, coastal and aimed at every level of rider — for many Victorians it is the first big day they ever ride.','2026-09-05'),
  ('amys-gran-fondo','Amy''s Great Ocean Road Gran Fondo','O2 Events, with the Amy Gillett Foundation','https://www.amysgranfondo.org.au/','Australia','Great Ocean Road, Victoria',null,'2026-09-13','September, annually','{3,45,90,122}'::integer[],null,'road','September','Run on closed sections of the Great Ocean Road between Lorne and Apollo Bay — one of the few chances to ride that coastline without traffic. A timed 122 km gran fondo sits alongside shorter recreational options and a 3 km family ride, in memory of Amy Gillett.','2026-09-05'),
  ('cape-to-cape-mtb','Cape to Cape MTB','EventMatrix','https://capetocapemtb.com/','Australia','Margaret River, Western Australia',null,'2026-10-15','October, annually','{200}'::integer[],2500,'mtb','October','Four days and roughly 200 km of coastal singletrack, farm tracks and forest through the Margaret River region, with daily stages of 34–59 km. Not especially technical, and the format deliberately builds in the breweries and wineries the region is known for.','2026-09-05'),
  ('maratona-dles-dolomites','Maratona dles Dolomites','Comitato Maratona dles Dolomites','https://www.maratona.it/en/','Italy','Alta Badia, Dolomites',null,'2027-07-04','First Sunday in July, annually','{55,106,138}'::integer[],null,'road','July','Seven Dolomite passes — Sella, Gardena, Campolongo, Pordoi, Falzarego, Giau among them — on roads closed to traffic for the day. Entry is by public ballot and heavily oversubscribed, so plan a year ahead rather than a month.','2026-09-05'),
  ('mallorca-312','Mallorca 312','Mallorca 312 OK Mobility','https://mallorca312.com/en/','Spain','Mallorca, Balearic Islands','mallorca','2027-04-24','Late April, annually','{167,226,312}'::integer[],null,'road','April','A closed-road day around much of the island, with three distances starting together from Playa de Muro — the 312 km option rolls out before dawn. Around 8,500 riders, mostly international, and it sells out quickly.','2026-09-05'),
  ('letape-du-tour','L''Étape du Tour de France','A.S.O.','https://www.letapedutourdefrance.com/en','France','Varies — follows a Tour de France mountain stage',null,null,'July, annually — route and date announced each spring','{}'::integer[],null,'road','July','Ride a genuine Tour de France mountain stage on closed roads, weeks before the professionals race it, with the race village and full support. The route changes every year, so check the official site for the current edition.','2026-09-05'),
  ('marmotte-granfondo-alpes','La Marmotte Granfondo Alpes','Cycling Classics','https://marmottegranfondoalpes.com/en/','France','French Alps',null,null,'Late June / early July, annually','{177}'::integer[],5000,'road','July','177 km and 5,000 m from Bourg-d''Oisans over the Glandon, Télégraphe and Galibier, finishing up the 21 hairpins of Alpe d''Huez. Shorter companion rides run the same weekend for anyone not ready to commit to the full day.','2026-09-05'),
  ('we-ride-flanders','We Ride Flanders','Flanders Classics','https://werideflanders.com/en/','Belgium','East Flanders',null,'2027-04-04','The Saturday before the professional Ronde van Vlaanderen','{79,133,163,247}'::integer[],null,'road','April','The cobbled bergs of the Tour of Flanders — the Oude Kwaremont, the Paterberg — ridden the day before the professionals race the same roads. Every route finishes in Oudenaarde; the longest starts in Antwerp.','2026-09-05'),
  ('gran-fondo-strade-bianche','Gran Fondo Strade Bianche','RCS Sports & Events','https://gfstradebianche.it/en/','Italy','Tuscany',null,'2027-03-08','March, annually','{87,138}'::integer[],2000,'gravel','March','The white gravel roads of the Crete Senesi, on the same course the professionals race, finishing in the Piazza del Campo in Siena. Mixed gravel and tarmac with a firm seven-hour cutoff on the long route.','2026-09-05'),
  ('haute-route-alps','Haute Route Alps','Haute Route','https://www.hauteroute.org/','France','French Alps',null,null,'August, annually — seven stages','{808}'::integer[],19255,'road','August','Seven timed stages across the Alps with a race convoy, mechanical and medical support and controlled roads — closer to a stage race than a sportive. Around 800 km and 19,000 m of climbing over some of the biggest passes in the range.','2026-09-05'),
  ('sea-otter-europe-girona','Sea Otter Europe Girona Gravel World Series','OciSport, with the UCI','https://gironagravelworldseries.com/en/home/','Spain','Catalonia','girona','2026-09-19','September, annually','{}'::integer[],null,'gravel','September','A UCI Gravel World Series qualifier on the Costa Brava gravel that made Girona a cycling town, run as part of the Sea Otter Europe festival. Distances are published in the technical guide each year rather than on the front page.','2026-09-05'),
  ('levis-granfondo','Levi''s GranFondo','Bike Monkey','https://www.levisgranfondo.com/','USA','Sonoma County, California',null,'2027-04-24','Late April, annually','{13,55,105,138,192}'::integer[],null,'road','April','Sonoma wine country and the coastal ridgelines above it — King Ridge and Meyers Grade — with five distances from a family ride to the 119-mile Growler. Founded by Levi Leipheimer and still one of the harder one-day road routes in the United States.','2026-09-05'),
  ('unbound-gravel','Unbound Gravel','Life Time','https://www.unboundgravel.com/','USA','Flint Hills, Kansas',null,'2027-06-04','First weekend in June, annually','{40,80,161,322,563}'::integer[],null,'gravel','June','Gravel racing''s biggest day, on the flint-studded roads of the Kansas Flint Hills, with the 200-mile distance as the one everyone means. Entry is by lottery, drawn the November before, and the rock is famous for destroying tyres.','2026-09-05'),
  ('leadville-trail-100-mtb','Leadville Trail 100 MTB','Life Time','https://www.leadvilleraceseries.com/mtb/leadvilletrail100mtb/','USA','Colorado',null,null,'Mid-August, annually — entry by lottery each December','{163}'::integer[],3017,'mtb','August','An out-and-back between Leadville and Twin Lakes entirely above 9,200 feet, topping out at 12,600 on the Columbine Mine climb. Entry is by lottery, and finishing inside the cutoff earns the belt buckle the race is built around.','2026-09-05'),
  ('sbt-grvl','SBT GRVL','SBT GRVL','https://www.sbtgrvl.com/','USA','Steamboat Springs, Colorado',null,'2027-06-25','Late June, annually','{40,85,118,174}'::integer[],2496,'gravel','June','High-altitude ranchland gravel out of the ski town of Steamboat Springs, graded from a 25-mile green ride to the 108-mile black course. Places are allocated by random draw in an open registration window rather than first come, first served.','2026-09-05'),
  ('sea-otter-classic','Sea Otter Classic','Life Time','https://www.seaotterclassic.com/','USA','Monterey, California',null,'2027-04-15','Mid-April, annually','{80,145}'::integer[],null,'mixed','April','Part bike festival, part race meeting: an enormous industry expo at Laguna Seca alongside road, cross-country, downhill, enduro and gravel racing plus two gran fondos. The trade sees it as the season''s product launch; riders see it as a weekend of racing anything they own.','2026-09-05'),
  ('belgian-waffle-ride-california','Belgian Waffle Ride California','Monuments of Cycling','https://www.belgianwaffleride.bike/pages/belgian-waffle-ride-ca','USA','Del Mar, California',null,null,'Early May, annually','{53,97,171}'::integer[],2286,'mixed','May','The original Belgian Waffle Ride: tarmac, dirt, sand and singletrack stitched into one deliberately awkward day out of the Del Mar Polo Fields. The headline Waffle route runs about 106 miles with 7,500 feet of climbing.','2026-09-05'),
  ('gfny-new-york','GFNY World Championship New York','Gran Fondo New York','https://nyc.gfny.com/','USA','New York / New Jersey',null,'2027-05-16','Mid-May, annually','{137}'::integer[],null,'road','May','A timed mass-start road race that begins on the George Washington Bridge and heads into Bergen and Rockland counties before finishing in Fort Lee. It is the final of GFNY''s global qualifying series, and riders come from more than ninety countries.','2026-09-05'),
  ('big-sugar-gravel','Big Sugar Gravel','Life Time','https://www.bigsugarclassic.com/gravel/','USA','Bentonville, Arkansas','bentonville','2026-10-17','Mid-October, annually','{48,87,160}'::integer[],1890,'gravel','October','The gravel season''s closer, on the loose, sharp limestone roads of the Ozarks north of Bentonville. The 100-mile route carries about 6,200 feet of climbing and often decides the Life Time Grand Prix standings.','2026-09-05'),
  ('taiwan-kom-challenge','Taiwan KOM Challenge','Taiwan Cyclist Federation','http://www.taiwankom.org/en/','Taiwan','Hualien County','hualien',null,'Late October, annually','{105}'::integer[],3275,'road','October','From sea level at Qixingtan Beach to 3,275 m at Wuling, Taiwan''s highest paved road, climbing the whole way through Taroko Gorge. Around 7% for 90 km, then ramps past 20% at the top — one of the hardest single climbs anywhere.','2026-09-05'),
  ('cycling-shimanami','Cycling Shimanami','Cycling Shimanami Executive Committee','https://cycling-shimanami.jp/english/','Japan','Setouchi','onomichi','2026-10-25','October, held every two years','{}'::integer[],null,'road','October','The one day the Shimanami Kaido expressway itself closes to cars so riders can use the main carriageway across the islands between Onomichi and Imabari. Several course options are offered; the bridges are the reason to come.','2026-09-05'),
  ('absa-cape-epic','Absa Cape Epic','Epic Series','https://www.epic-series.com/races/capeepic','South Africa','Western Cape',null,'2027-03-21','March, annually — eight days','{650}'::integer[],15500,'mtb','March','Eight days and roughly 650 km through the Western Cape, ridden in pairs who must finish together. UCI hors catégorie, and generally treated as the hardest mountain bike stage race in the world.','2026-09-05'),
  ('cape-town-cycle-tour','Cape Town Cycle Tour','Cape Town Cycle Tour Trust','https://www.capetowncycletour.com/','South Africa','Western Cape',null,'2027-03-14','March, annually','{42,109}'::integer[],null,'road','March','A fully closed 109 km loop of the Cape Peninsula, run every year since 1978 and the largest timed individual cycling event in the world. A 42 km option covers part of the same coastline.','2026-09-05'),
  ('tour-de-bintan','Tour de Bintan','Bintan Resorts','https://tourdebintan.id/','Indonesia','Bintan Island',null,null,'August, annually','{17,45,70,100,150}'::integer[],null,'road','August','A three-day road weekend on Bintan with five formats from a 17 km time trial to a 150 km gran fondo, carrying UCI Gran Fondo World Series status. An easy ferry from Singapore, which is much of its appeal.','2026-09-05'),
  ('come-bikeday-sun-moon-lake','Come! BikeDay Sun Moon Lake','Sun Moon Lake National Scenic Area Administration','https://theme.sunmoonlake.gov.tw/ComeBikeDay/Index.aspx?l=2','Taiwan','Nantou County','sunmoonlake',null,'Year-round programme, with an annual carnival','{30}'::integer[],null,'road','Year-round','A government-run cycling programme around the 30 km lake loop rather than a single race, with an annual carnival and a cross-lake ferry return. Worth knowing about if you are planning the ride rather than chasing a number.','2026-09-05'),
  ('chiang-mai-gran-fondo','Chiang Mai Gran Fondo','55 Cycling Club','https://chiangmaigranfondo.com/','Thailand','Chiang Mai Province','chiangmai','2026-12-13','December, annually','{25,50,80,120}'::integer[],null,'road','December','The established mass-participation gran fondo in northern Thailand, part of the Gran Fondo World Series, starting from PAO Park with four distances. December puts it in the cool, dry season, which is why it works.','2026-09-05')
on conflict (slug) do nothing;   -- safe to re-run; never overwrites an edit made in the admin
